Upgrade yarn.lock for google-auth-library to use gtoken@4.1.3
Version 4.1.2 breaks typescript builds with "error TS1086: An accessor cannot be declared in an ambient context."
https://github.com/googleapis/node-gtoken/issues/244